version: "3.0.0"

# Your Wi-Fi's SSID and password
# see: https://esphome.io/components/wifi
wifi_ssid: <redacted>
wifi_password: <redacted>

ssid1_pswd: <redacted>
ssid1_name: <redacted>

ssid2_pswd: <redacted>
ssid2_name: <redacted>

ssid3_pswd: <redacted>
ssid3_name: <redacted>

ssid4_pswd: <redacted>
ssid4_name: <redacted>

# domain
# Set the domain of the node hostname used for uploading.
# For example, if it’s set to .local, all uploads will be sent to <HOSTNAME>.local
domain: .local

# Passwords for appl, ota
see: https://esphome.io/components/wifi
app_pswd: <redacted>
# see: https://esphome.io/components/ota
ota_pswd: <redacted>
hotspot_pswd: <redacted>

# UDP server wmbusmeter
# see: https://github.com/SzczepanLeon/esphome-components#211-example-for-version-2x
wmbus_server:  <redacted>
wmbus_server_port: 7337

# Backup
# see: https://github.com/zdzichu6969/esphome-components
web_username: <redacted>
web_password: <redacted>

# Watermeter ID, only HEX is working for me
# meter_id (Required, int): Meter ID (usually from sticker).
# Can be specified as decimal or hex.
watermeterId: 0x43430778
watermeterIx: 18444343

# Using wmbusmeters i a pipe
# see: https://github.com/wmbusmeters/wmbusmeters#using-wmbusmeters-in-a-pipe
watermeterhost: <redacted>
wmbusmeter_host: <redacted>

# service host target (runUDPServer)
# see: https://github.com/zibous/ha-watermeter/blob/master/tools/simpleserver.py
service_host: <redacted>
data_host: <redacted>

# syslog, enable this if you have a syslog server
# see: https://github.com/TheStaticTurtle/esphome_syslog
syslog_server: <redacted>
syslog_port: <redacted>

# WEBSERVER settings
# see: https://github.com/zibous/ha-watermeter/tree/master/esphome/webserver

# webserver 3.0 change url to your webserver
webserver_jsurl:  "https://raw.githubusercontent.com/zibous/ha-watermeter/b0e3ed3f9b7c9f8da74bfe37389cee26ec8358e3/esphome/webserver/v3/www.js"
webserver_cssurl: "https://raw.githubusercontent.com/zibous/ha-watermeter/b0e3ed3f9b7c9f8da74bfe37389cee26ec8358e3/esphome/webserver/v3/webserver.css"

# webserver v2 change url to your webserver
# if you have homeassistant installed, you can use it as webserver
# copy the webserver to the homeassistant www folder and use:
# http://homeassistant.local:8123/www/esphome/webserver/v3/www.js
webserver2_jsurl:  "http://homeassistant.local:8123/local/esphome/v2/www.js"

# webserver v2 change url to your webserver
# if you have homeassistant installed, you can use it as webserver
# copy the webserver to the homeassistant www folder and use:
# http://homeassistant.local:8123/www/esphome/webserver/v3/www.js
webserver3_jsurl:  "http://homeassistant.local:8123/local/esphome/v3/www.js"

# webserver v1 change url to your webserver
webserver1_jsurl:  "https://espweb.local/esphome/v2/webserver-v1.js"
webserver1_cssurl: "https://espweb.local/esphome/v1/webserver-v1.css"
